// Generated by CoffeeScript 1.6.2
(function() {
  var http, onRequest, url;

  http = require('http');

  url = require('url');

  onRequest = function(request, response) {
    var pathname;

    pathname = url.parse(request.url).pathname;
    console.log('Request for', pathname, 'received.');
    if (pathname === '/start') {
      response.writeHead(200, {
        'Content-Type': 'text/plain'
      });
      response.write('Hello');
      return response.end();
    } else if (pathname === '/finish') {
      response.writeHead(200, {
        'Content-Type': 'text/plain'
      });
      response.write('Goodbye');
      return response.end();
    } else {
      response.writeHead(404, {
        'Content-Type': 'text/plain'
      });
      return response.end('404 Not Found');
    }
  };

  http.createServer(onRequest).listen(9999);

  console.log('Server has started.');

}).call(this);
